security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
          entity:
              class: App\Entity\User
              property: email
    firewalls:
      login:
          user_checker: App\Security\UserChecker
          pattern: ^/api/login
          stateless: true
          json_login:
              check_path: /api/login
              username_path: email
              password_path: password
              success_handler: lexik_jwt_authentication.handler.authentication_success
              failure_handler: lexik_jwt_authentication.handler.authentication_failure
      main:
        lazy: true
        stateless: true
        user_checker: App\Security\UserChecker
        jwt: # JWT authentication
          provider: app_user_provider

    access_control:
      - { path: ^/admin, roles: ROLE_ADMIN }
      - { path: ^/user, roles: IS_AUTHENTICATED_FULLY }
