security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
          entity:
              class: App\Entity\User
              property: email
    firewalls:
      main:
        lazy: true
        stateless: true
        provider: app_user_provider
        json_login:
          check_path: /api/login
          username_path: email
          password_path: password
        logout:
          path: /api/logout
          invalidate_session: false


    access_control:
      - { path: ^/admin, roles: ROLE_ADMIN }
      - { path: ^/user, roles: IS_AUTHENTICATED_FULLY }
