_security_logout:
    resource: security.route_loader.logout
    type: service

firewalls:
    main:
        lazy: true
        provider: app_user_provider
        form_login:
            login_path: login
            check_path: login
            username_parameter: email
            password_parameter: password
            enable_csrf: false
        logout:
            path: /logout
            invalidate_session: true
        user_checker: App\Security\UserChecker

access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/user, roles: IS_AUTHENTICATED_FULLY }
